### ISSUE TITLE
No examples included 

### ISSUE THREAD

**Issue by justinpando** [jlreymendez/planilo#1]
The readme says there are examples to look at, but there aren't any so I'm having a hard time understanding how to get started.

**Comment by jlreymendez** [comment]
Hi justipando, sorry I didn't answer before. You are completely right, there are no examples in the repo, I wonder what I was thinking when I wrote that. 
I'm in the process of updating this project to a newer version of xNode and adding some funcionality. I'll try to add a few examples for real this time. Thanks for bringing this to my attention.
