### ISSUE TITLE
About dropping xNode

### ISSUE THREAD

**Issue by technologicalMayhem** [jlreymendez/planilo#10]
So this isn't really an issue, more a question about the statement in the readme about the development being discontinued.

I recently started using this and only now saw that this has been discontinued. I wanted to put in some own work to extend and modify this for my own purposes but i saw that you have stated that if you were to continue on this you would need to drop xNode. I wanted to ask about what reasons you have for that. If i were to continue development on this myself it would be bad if i spend many hours on it just to come to the same conclusion if i could have just asked about it.

**Comment by jlreymendez** [comment]
I have encountered serialization problems multiple times, not sure if I can blame xNode for it or if it's a problem with how I am using it. The samples not serializing correctly was the last straw for me, I would only continue this if I had full control over the serialization process. And now that Unity's graph system is a bit more available I would try to use that for the visualization part.
