### ISSUE TITLE
How do you access keys for existing blackboard nodes(ones that that have been added in editor mode and not runtime)?

### ISSUE THREAD

**Issue by BDeshiDev** [jlreymendez/planilo#2]
The key for them is not the same as the node's name. I see no other way to get the keys.
Ex: I add a blackboard bool node in the graph. name of the node is set to "Test".  Using AIRunnerInstance.GetFromBlackboard("Test") returns null.  If the node name is not the key then what is?

**Comment by jlreymendez** [comment]
Hi BDeshiDev, I'm in the process of updating this project to a newer version of xNode and adding some funcionality. I'll get back to you with an answer. It's been a while since I wrote this.

**Comment by jlreymendez** [comment]
Hi BDeshiDev, You are correct in assuming that the key of the blackboard variable is the same as the node's name. Only thing I can think of is that the variable hasn't been set, in that case it will be returned as null. You can set the variable from outside the Graph using `AIRunnerInstance.SetInBlackboard("Test", true);` or you can set it from an inside node using either BT.Blackboard["Test"] = true (or FSM.Blackboard depending on what you are using)
