### ISSUE TITLE
how abort type?

### ISSUE THREAD

**Issue by matrix3d** [jlreymendez/planilo#7]

**Comment by jlreymendez** [comment]
I don't understand your question.

**Comment by matrix3d** [comment]
```
namespace Planilo.BT
{
    public enum AbortType
    {
        None,
        Self,
        LowerPriority,
        Both
    }
}
```

https://opsive.com/support/documentation/behavior-designer/conditional-aborts/


I have implemented this feature, can I submit it?

**Comment by jlreymendez** [comment]
You can make the PR, I will evaluate it. But I think you can achieve similar effects with the ActiveSelector node.

**Comment by matrix3d** [comment]
There is still a certain gap between the two class
